require_relative "vk_longpoll_bot/utility.rb"
require_relative "vk_longpoll_bot/constants.rb"
require_relative "vk_longpoll_bot/exceptions.rb"
require_relative "vk_longpoll_bot/request.rb"
require_relative "vk_longpoll_bot/bot.rb"
require_relative "vk_longpoll_bot/events.rb"